version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQQ_GIT_Project_NewProject
  gitServerName: rimaSCSiqa
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
